const basketTypes = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",

  REMOVE_FROM_CART_REQUEST: "REMOVE_FROM_CART_REQUEST",
  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR",

  INCREMENT_ITEM_REQUEST: "INCREMENT_ITEM_REQUEST",
  INCREMENT_ITEM_SUCCESS: "INCREMENT_ITEM_SUCCESS",
  INCREMENT_ITEM_ERROR: "INCREMENT_ITEM_ERROR",

  DECREMENT_ITEM_REQUEST: "DECREMENT_ITEM_REQUEST",
  DECREMENT_ITEM_SUCCESS: "DECREMENT_ITEM_SUCCESS",
  DECREMENT_ITEM_ERROR: "DECREMENT_ITEM_ERROR",
};

export default basketTypes;
