const productTypes = {
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_ERROR: "PRODUCT_LIST_ERROR",

  PRODUCT_DETAIL_REQUEST: "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS: "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_ERROR: "PRODUCT_DETAIL_ERROR",

  CATEGORY_LIST_REQUEST: "CATEGORY_LIST_REQUEST",
  CATEGORY_LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
  CATEGORY_LIST_ERROR: "CATEGORY_LIST_ERROR",

};

export default productTypes;
